### PR TITLE
Add save schema feature

### PR DESCRIPTION
**Pull request by Quramy**
To develop react-relay application schema.json is required([https://facebook.github.io/relay/docs/guides-babel-plugin.html#schema-json](https://facebook.github.io/relay/docs/guides-babel-plugin.html#schema-json).

I think it's nice to fetch and save the schema using GraphiQL app.

### CODE REVIEW

**Comment by Quramy** [comment]
@skevy , how about it?

**Comment by skevy** [comment]
Hi @Quramy thanks for this PR! I've been traveling -- but I'll attempt to get this reviewed today!

**Comment by skevy** [comment]
Hi @Quarmy I just tried this out. It seems to work well, but the design doesn't work with the more recent updates.

I know it's been forever, but are you still interested in getting this in?

**Comment by Quramy** [comment]
@skevy, thanks for your reply! Absolutely yes.
Ok, I'll update this PR. Then would you re-review it?

**Comment by skevy** [comment]
Yes definitely ! @Quramy

**Comment by Quramy** [comment]
Hi, @skevy . I've updated this PR and moved this feature under the File menu. How about it ?

**Comment by gjtorikian** [comment]
@Quramy I'm really sorry for the great delay here. Would you mind resolving the conflicts so it can be merged? 🙏

**Comment by gjtorikian** [comment]
Closing as stale.

**Pull request closed without merging**
