### PR TITLE
Upgarded graphiql, graphql, electron & webpack.

### PR DESCRIPTION
**Pull request by akshah123**
Upgraded different packages so that we can leverage their latest functionality.

### CODE REVIEW

**Comment by skevy** [comment]
@akshah123 Does this fully build and run? Any chance you could attach a DMG that I could test?

**Comment by akshah123** [comment]
@skevy I am on windows so I can't get you a DMG.  I can get you windows build or WSL build on ubuntu.

**Comment by akshah123** [comment]
@skevy I was able to package on a different laptop.   However, it's 58 MB, how can I share it with you?

**Comment by akshah123** [comment]
@skevy try this: https://we.tl/t-KE9frwaoI4

**Comment by akshah123** [comment]
@skevy was that helpful?  Did it work for you?

**Comment by akshah123** [comment]
@skevy just pinging it to bring it back to your attention.

**Pull request merged**
