### PR TITLE
Allow editing headers

### PR DESCRIPTION
**Pull request by andrefgneves**
Hi,

here's a quick go at modifying HTTP headers (#11).

### CODE REVIEW

**Comment by gjtorikian** [comment]
Nice!

Have you tried running the test locally. Curious to know why it broke.

**Comment by andrefgneves** [comment]
I did and they pass. Not sure why they fail on Travis.

screen shot

**Comment by gjtorikian** [comment]
Well, I confirmed that locally this does what the PR says, so thanks!

I know this problem existed before this PR, but would you mind expanding the value text box so that it fits the length of the table? It was weird when adding a header value, but now I think the problem is exacerbated when trying to edit!

**Comment by andrefgneves** [comment]
Done

**Comment by gjtorikian** [comment]
Aaaand the test passes because magic. Cool, cool. 

Thank you!

**Comment by hardchor** [comment]
Has this been released yet?

**Comment by kimegede** [comment]
@hardchor it was merged into master the 16th September.

**Comment by gjtorikian** [comment]
I don't think it was released yet. I'll try to deploy one when I get the chance.

**Comment by astanciu** [comment]
still no release?

**Pull request merged**
