### PR TITLE
add the close query menu item for non-macOS

### LINKED ISSUE #70: how to close a query tab ?
tks

### PR DESCRIPTION
**Pull request by shiftkey**
Fixes #70 

 - [x] add in the missing menu item and keybinding

### CODE REVIEW

**Comment by shiftkey** [comment]
cc @gjtorikian

**Comment by gjtorikian** [comment]
> menu is platform specific, should review this

I'm ready to merge, but as a not-Electron developer, what does this entail?

**Comment by shiftkey** [comment]
@gjtorikian at the moment the menu is rendered differently per-platform (this is fine), but the `File` menu on Windows/Linux is incomplete: https://github.com/skevy/graphiql-app/blob/master/main.js#L190-L197 

So the current change doesn't even fix that, and it'd be nice to reduce the duplication I think a bit of maintainability in here while I'm cleaning that up.

**Comment by shiftkey** [comment]
Ready for review

**Comment by gjtorikian** [comment]
Thank you!

**Pull request merged**
