### PR TITLE
main: fix "help" menu

### LINKED ISSUE #68: Uncaught Exception: Error: Cannot find module 'shell'
Using `0.5.1`, if you click [Help -> Search Issues](https://user-images.githubusercontent.com/571265/27497750-1475a9c0-5811-11e7-84bc-50ed804bcf30.png), the app will crash with an uncaught:

screen shot 2017-06-23 at 12 40 27

### PR DESCRIPTION
**Pull request by stephenmathieson**
This patch fixes the "help" menu by brining in the `shell` dependency. It also slightly refactors the usage of the module to ensure this does not happen again.

Closes #68.

### CODE REVIEW

**Comment by stephenmathieson** [comment]
bump

**Comment by gjtorikian** [comment]
I tested this out, but got a dialog box with:

image

Any thoughts on why `openExternal` wouldn't exist?

**Comment by skevy** [comment]
cc @stephenmathieson

**Comment by stephenmathieson** [comment]
huh, very strange. looks like this never worked.

closing for now.

**Pull request closed without merging**
