### PR TITLE
Support Cookies

### LINKED ISSUE #40: Send cookie via withCredentials option
When I add a custom header for `Cookie` it doesn't seem to work and gets automatically stripped before hitting the server. I think we need to enable `withCredentials` option in `fetch`.

### PR DESCRIPTION
**Pull request by brandonbloom**
Fixes #40.

See this corresponding change in express-graphql: https://github.com/graphql/express-graphql/pull/30

### CODE REVIEW

**Comment by brandonbloom** [comment]
A word of warning: I haven't actually tested this change locally. I made it directly on GitHub, sorry about that.

**Comment by skevy** [comment]
Thanks!!

**Comment by kevinold** [comment]
@brandonbloom Yeah, I'm needing this support too, but when I develop locally, it's not sending a 'Cookies' header to my GraphQL endpoint.  See https://github.com/electron/electron/issues/1606 for a bug with electron not supporting Cookies header.  I've tried bundling https://www.npmjs.com/package/electron-cookies but doesn't seem to work.

Ideas?

**Comment by kevinold** [comment]
I have found away around this by setting cookies in the mainWindow -- see https://github.com/kevinold/graphiql-app/commit/9cd8d6d6f507892acea056476bf679175adb77a7

I'll iterate and open a PR when I like the implementation.

Right now you must set "Cookie" key then "URL!!!NAME!!!VAL" and it's a bit wonky.

Any suggestions are welcome.

**Comment by twolfson** [comment]
For anyone curious, another alternative is to open your development site via `window.open('my-site')` in dev tools and perform any necessary logins there

**Pull request merged**
